### ISSUE TITLE
Part of the "specs" page can't be interacted with

### ISSUE THREAD

**Issue by ashtneoi** [httpwg/httpwg.github.io#14]
On the [specs page](https://httpwg.org/specs/), under the heading "Extension Registries", the two lines containing "HTTP Cache Directory Registry" and "HTTP Parameters" can't be interacted with. Specifically:
- I can't select the text by dragging the cursor (on Firefox, it selects part of the "Related Specifications" heading instead; on Chromium it does nothing)
- hovering over the links doesn't show a link preview and my cursor doesn't change to the link-hover cursor
- clicking the links does nothing

My OS is Ubuntu 18.04.1 with XFCE. I tested with Firefox 64.0 and Chromium 71.0.3578.98.

**Comment by mnot** [comment]
Hi,

I've just tested with latest Firefox, Chrome and Safari, and don't see any issues.

Do you have any browser extensions installed?

**Comment by ashtneoi** [comment]
I have a couple extensions in Firefox. I disabled those and see the same behavior. I don't have any Chromium extensions installed.

I only see this problem when the browser window is narrow enough that the content is shown in a single column. (I think the threshold is around 992 px.) Sorry for not noticing that originally.

**Comment by mnot** [comment]
I can reproduce that; thanks. Should have a fix shortly.
