### ISSUE TITLE
HTML page for RFC 7694 numbered incorrectly

### ISSUE THREAD

**Issue by awwright** [httpwg/httpwg.github.io#15]
The page for "Hypertext Transfer Protocol (HTTP) Client-Initiated Content-Encoding ", [RFC 7694](https://www.rfc-editor.org/rfc/rfc7694.txt), is provided as HTML on the website: https://github.com/httpwg/httpwg.github.io/blob/master/specs/rfc7694.xml

The document has the correct filename, but the RFC number defined inside the document refers to 7725, a different (HTTP-related) RFC.

**Comment by mnot** [comment]
Fixed thanks.
