### ISSUE TITLE
Specs TOC scrolling issues

### ISSUE THREAD

**Issue by Malvoz** [httpwg/httpwg.github.io#17]
Hello HTTPWG! :)

Currently, the specifications' TOC is near unscrollable unless you're at the end of scroll-position on the document's overflow.

I've been fiddling a bit but refrained from making a PR... here's an example snippet making the TOC scrollable, aswell as hiding its scrollbar. Perhaps you can test it and see how you like it.

```
#sidebar {
  position: fixed; /* I tried another approach using `.sticky-top` but scrolling felt janky. */
  top: 0;
  right: 0;
  height: 92vh;
  margin-top: 8vh;
  padding-top: 2rem;
  -ms-overflow-style: none; /* Hide scrollbars on overflow in IE/Edge. */
  scrollbar-width: none; /* Standard way to hide scrollbars on overflow (impl. only in Firefox atm). */
}

#sidebar::-webkit-scrollbar { /* Hide scrollbars on overflow in Chrome and other Webkit-based browsers. */
  display: none;
}

#sidebar .navbar {
  height: 90vh;
  max-width: 20rem;
}

#sidebar .nav {
  flex-direction: column;
  padding-bottom: 2rem;
}
```

**Comment by martinthomson** [comment]
@mnot, I can confirm this.  I can't scroll the TOC in [RFC7231](https://httpwg.org/specs/rfc7231.html).  Drafts don't suffer from the same problem ([e.g.](https://httpwg.org/http-extensions/draft-ietf-httpbis-digest-headers.html)), but I haven't spent time on working out why.

**Comment by mnot** [comment]
Yep; this is a result of the upgrade to Bootstrap 4. Will get to it, but probably not today.

**Comment by mnot** [comment]
Updated. Thanks for the report.
