### ISSUE TITLE
Twitter account banned and site being marked suspicious by URL scanners

### ISSUE THREAD

**Issue by Lagg** [httpwg/httpwg.github.io#19]
Hello, I'm trying to track and figure out the HTTP/2 specs insomuch as one man can figure out the structure of a toenail of a colossus built by 10 cities in 5 nights while trying to run his small farming business - but I digress.

It appears that the `@http_wg` twitter account was suspended. This is reproducible by going [here](https://twitter.com/http_wg). Due to the general complexity of this veritable specification (and specification density) firehose, maybe I've somehow lost my way between research sources and landed on a fake site? It's quite easy with HTTP/2 you know.

*Edit:* Merging redundant post, [this](https://http2.github.io/) site doesn't use the apparent-canonical domain.

*Double edit:* You will have to forgive my excessive sass in this bug report as I have within the last several days found out that Google managed to reinvent SWF objects in the form of WebAssembly and then managed to create an entirely new stack layer under HTTP. The spirit of the report is sincere and submitted in case there is some kind of shared database for suspicious domains and this is representative of a problem especially given the twitter ban.

**Comment by Lagg** [comment]
This cookiecutter crap is getting really old for someone just trying to research the specs. Does [this](https://http2.github.io/) site have any connection to the other [bootstrap default demo](https://httpwg.org/) or is this a tagalong that someone forgot to set a redirect for and I shouldn't trust the spec links as canonical?

**Comment by Lagg** [comment]
Update on the URL scanner issue: I had previously posted a screenshot of Steam's "suspicious URL" tag on the httpwg.org domain which gave me cause to track down the repo in the first place. I've sent a note of this to someone on my list so that it can at least be added to a whitelist or something. It turns out to be a very bad heuristic. 
![why](https://user-images.githubusercontent.com/2509793/63065467-03988600-bebb-11e9-9b5f-67539c9f4e44.png)

**Comment by Lagg** [comment]
Well this is embarassing. Either someone read this issue and contacted twitter's support or it was a very strange coincidence. But it seems that the twitter account is no longer suspended either. I suppose the issue can be considered closed.

**Comment by mnot** [comment]
Hi. There was indeed a problem with the twitter account; apologies. That's been fixed; thanks for the report.
