### ISSUE TITLE
htttp2bis link is broken

### ISSUE THREAD

**Issue by LPardue** [httpwg/httpwg.github.io#28]
On the homepage httpwg.org, the link to "HTTP/2 Revision" is broken. I think this is due to the recent renaming of the document to it's RFC number. The link that appears to work is https://httpwg.org/http2-spec/rfc9113.html

cc: @martinthomson @Lukasa

**Comment by Lukasa** [comment]
Yup, that sounds right.

**Comment by reschke** [comment]
FWIW, I try to avoid renaming files into rfcxxxx until the RFC is actually published...

**Comment by mnot** [comment]
Yes - we'll generate /specs/rfcxxxx.html when it's published, but that's separate. Can you please change it back?

**Comment by martinthomson** [comment]
Done.
