### ISSUE TITLE
rfcbootstrap.xslt

### ISSUE THREAD

**Issue by reschke** [httpwg/httpwg.github.io#7]
This is bad; it's a fork of rfc2629.xslt that is hacked & unmaintained (apparently).

**Comment by mnot** [comment]
No, it's not/RFCBootstrap (as I told you when I did it).

**Comment by reschke** [comment]
Well, it claims that it's my code in the copyright. It puts in rfc2629.xslt's generator string. It's behind rfc2629.xslt approximately 11 months. It might not be able to process the latest XML source properly.

**Comment by mnot** [comment]
Well, if you had a proper repo for it, it'd be easier to keep in sync :)

Happy to take pull requests to fix attribution as you'd prefer, or to do it myself if you have no preference.

**Comment by reschke** [comment]
https://github.com/httpwg/http-extensions/tree/master/lib has snapshots.

The main issue here is to take a large piece of code and just to start hacking on it. What should have been done is to identify what features are needed, and to either integrate them in the core, or put them into an overlay XSLT that just imports from rfc2629.xslt.

And yes, please fix the copyright and what ever gets inserted as generator string.
